;
; File generated by cc65 v 2.18 - Git N/A
;
	.fopt		compiler,"cc65 v 2.18 - Git N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_putchar
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	lda     #$41
	jsr     pusha
	ldx     #$00
L0015:	txa
L0017:	ldy     #$01
	jsr     staxysp
	cmp     #$00
	txa
	sbc     #$7D
	bvc     L000E
	eor     #$80
L000E:	bpl     L0008
	lda     (sp)
	ldx     #$00
	jsr     _putchar
	ldy     #$02
	jsr     ldaxysp
	ina
	bne     L0017
	inx
	bra     L0017
L0008:	ldx     #$00
	lda     (sp)
	ina
	sta     (sp)
	bra     L0015

.endproc

